#include "inc_composite_queue.h"

void IncCompositeQueue::receivePacket(Packet& pkt) {
    if (pkt._is_inc) {
        // cout << "DEBUG_COMP: Packet INC (" << pkt._inc_block_id << ") arrived at " << _nodename << endl;
        
        if (_switch) {
             // Interception condition: if the packet was NOT just generated by this switch
             if (pkt._inc_last_switch_id != (int)_switch->getID()) {
                 // cout << "   -> INTERCEPTION TRIGGERED! Handing over to switch." << endl;
                 _switch->receivePacket(pkt);
                 return;
             }
        }
    }
    CompositeQueue::receivePacket(pkt);
}
